spring:
  application:
      name: client-feign

server:
  port: 8003

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8000/eureka/

ribbon:
   eureka:
      enable: true
   eager-load:
      enabled: true
      clients: service-provider
    
hystrix:
   command:
      default:
         execution:
            thread:
               timeoutInMilliseconds: 5000